name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:  # Allow this workflow to be called by other workflows

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        shell: bash
        run: |
          # Clone all workspace member repos (meta-repo architecture)
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-${{ matrix.os }}"

      - name: Run tests
        run: cargo test --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        run: |
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "clippy"

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

  integration:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        run: |
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "integration-${{ matrix.os }}"

      - name: Build workspace
        run: cargo build --workspace

      - name: Verify binaries
        run: |
          ls -lh target/debug/meta target/debug/meta-git
          ./target/debug/meta --version
          ./target/debug/meta-git --meta-plugin-info | jq .name
        shell: bash

      - name: Install bats
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y bats
          else
            brew install bats-core
          fi
        shell: bash

      - name: Run integration tests
        run: bats tests/*.bats
        shell: bash

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        run: |
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check
# Testing CI with config fix
