name: On Child Repo Update

on:
  repository_dispatch:
    types: [child-repo-updated]
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Child repo name'
        required: true
        default: 'test-repo'
      short_sha:
        description: 'Short SHA'
        required: true
        default: 'abc1234'
      message:
        description: 'Commit message'
        required: true
        default: 'feat: test commit'
      type:
        description: 'Commit type'
        required: true
        default: 'feat'
      actor:
        description: 'Actor'
        required: true
        default: 'test-user'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-sync-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_WRITE_PACKAGES_PAT }}

      - name: Extract payload
        id: payload
        env:
          EVENT_NAME: ${{ github.event_name }}
          DISPATCH_REPO_NAME: ${{ github.event.client_payload.repo_name }}
          DISPATCH_SHORT_SHA: ${{ github.event.client_payload.short_sha }}
          DISPATCH_MESSAGE: ${{ github.event.client_payload.message }}
          DISPATCH_TYPE: ${{ github.event.client_payload.type }}
          DISPATCH_ACTOR: ${{ github.event.client_payload.actor }}
          INPUT_REPO_NAME: ${{ github.event.inputs.repo_name }}
          INPUT_SHORT_SHA: ${{ github.event.inputs.short_sha }}
          INPUT_MESSAGE: ${{ github.event.inputs.message }}
          INPUT_TYPE: ${{ github.event.inputs.type }}
          INPUT_ACTOR: ${{ github.event.inputs.actor }}
        run: |
          write_output() {
            local key="$1" value="$2"
            local delim="__EOF__$(date +%s%N)_$RANDOM"
            {
              printf '%s<<%s\n' "$key" "$delim"
              printf '%s\n' "$value"
              printf '%s\n' "$delim"
            } >> "$GITHUB_OUTPUT"
          }

          # Handle both repository_dispatch and workflow_dispatch
          if [ "$EVENT_NAME" = "repository_dispatch" ]; then
            write_output repo_name "$DISPATCH_REPO_NAME"
            write_output short_sha "$DISPATCH_SHORT_SHA"
            write_output message "$DISPATCH_MESSAGE"
            write_output type "$DISPATCH_TYPE"
            write_output actor "$DISPATCH_ACTOR"
          else
            write_output repo_name "$INPUT_REPO_NAME"
            write_output short_sha "$INPUT_SHORT_SHA"
            write_output message "$INPUT_MESSAGE"
            write_output type "$INPUT_TYPE"
            write_output actor "$INPUT_ACTOR"
          fi

      - name: Create sync commit
        env:
          REPO_NAME: ${{ steps.payload.outputs.repo_name }}
          SHORT_SHA: ${{ steps.payload.outputs.short_sha }}
          MESSAGE: ${{ steps.payload.outputs.message }}
          TYPE: ${{ steps.payload.outputs.type }}
          ACTOR: ${{ steps.payload.outputs.actor }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Strip the "type: " prefix from the message if present
          CLEAN_MSG="${MESSAGE#*: }"

          git commit --allow-empty -m "${TYPE}(${REPO_NAME}): ${CLEAN_MSG}

          Synced from ${REPO_NAME}@${SHORT_SHA}

          Co-authored-by: ${ACTOR} <${ACTOR}@users.noreply.github.com>"

          git push

      - name: Log sync
        env:
          EVENT_NAME: ${{ github.event_name }}
          REPO_NAME: ${{ steps.payload.outputs.repo_name }}
          SHORT_SHA: ${{ steps.payload.outputs.short_sha }}
          TYPE: ${{ steps.payload.outputs.type }}
          MESSAGE: ${{ steps.payload.outputs.message }}
        run: |
          echo "Event: $EVENT_NAME"
          echo "Repo: $REPO_NAME"
          echo "SHA: $SHORT_SHA"
          echo "Type: $TYPE"
          echo "Message: $MESSAGE"
