name: Release

on:
  push:
    tags:
      - 'v*'
  repository_dispatch:
    types: [release-tagged]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            binary_name: meta
            asset_name: meta-darwin-x64.tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            binary_name: meta
            asset_name: meta-darwin-arm64.tar.gz
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary_name: meta
            asset_name: meta-linux-x64.tar.gz
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            binary_name: meta
            asset_name: meta-linux-arm64.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary_name: meta.exe
            asset_name: meta-windows-x64.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        shell: bash
        run: |
          # Clone all workspace member repos (meta-repo architecture)
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools (Linux ARM)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          mkdir -p .cargo
          cat >> .cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build release binaries
        run: |
          cargo build --release --target ${{ matrix.target }} -p meta
          cargo build --release --target ${{ matrix.target }} -p meta_git_cli
          cargo build --release --target ${{ matrix.target }} -p meta_project_cli
          cargo build --release --target ${{ matrix.target }} -p meta-mcp
          cargo build --release --target ${{ matrix.target }} -p loop_cli

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} dist/
          cp target/${{ matrix.target }}/release/meta-git dist/
          cp target/${{ matrix.target }}/release/meta-project dist/
          cp target/${{ matrix.target }}/release/meta-mcp dist/
          cp target/${{ matrix.target }}/release/loop dist/
          cd dist
          tar -czvf ../${{ matrix.asset_name }} *
          cd ..
          shasum -a 256 ${{ matrix.asset_name }} > ${{ matrix.asset_name }}.sha256

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir dist
          copy target\${{ matrix.target }}\release\${{ matrix.binary_name }} dist\
          copy target\${{ matrix.target }}\release\meta-git.exe dist\
          copy target\${{ matrix.target }}\release\meta-project.exe dist\
          copy target\${{ matrix.target }}\release\meta-mcp.exe dist\
          copy target\${{ matrix.target }}\release\loop.exe dist\
          cd dist
          7z a -tzip ..\${{ matrix.asset_name }} *
          cd ..
          certutil -hashfile ${{ matrix.asset_name }} SHA256 > ${{ matrix.asset_name }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: |
            ${{ matrix.asset_name }}
            ${{ matrix.asset_name }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Get tag name
        id: get-tag
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        run: |
          mkdir -p release
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" \) -exec cp {} release/ \;
          cd release
          cat *.sha256 > checksums.txt

      - name: Upload to existing release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-tag.outputs.tag }}
          files: release/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to crates.io
    needs: release
    runs-on: ubuntu-latest
    # Only publish on non-prerelease tags
    if: ${{ !contains(needs.release.outputs.tag, '-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone child repos
        run: |
          git clone --depth 1 https://github.com/harmony-labs/loop_lib.git
          git clone --depth 1 https://github.com/harmony-labs/loop_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_core.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_git_lib.git
          git clone --depth 1 https://github.com/harmony-labs/meta_mcp.git
          git clone --depth 1 https://github.com/harmony-labs/meta_plugin_protocol.git
          git clone --depth 1 https://github.com/harmony-labs/meta_rust_cli.git
          git clone --depth 1 https://github.com/harmony-labs/meta_project_cli.git

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Publish in dependency order
      # Tier 1: No internal dependencies
      - name: Publish loop_lib
        run: cargo publish -p loop_lib --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true  # May already be published

      - name: Publish meta_plugin_protocol
        run: cargo publish -p meta_plugin_protocol --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      - name: Publish meta_core
        run: cargo publish -p meta_core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      # Tier 2: Depends on tier 1
      - name: Publish loop_cli
        run: cargo publish -p loop_cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      - name: Publish meta
        run: cargo publish -p meta --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      # Tier 3: Depends on meta
      - name: Publish meta_git_lib
        run: cargo publish -p meta_git_lib --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      # Tier 4: Depends on meta_git_lib
      - name: Publish meta_git_cli
        run: cargo publish -p meta_git_cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      - name: Publish meta_project_cli
        run: cargo publish -p meta_project_cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

      - name: Publish meta-mcp
        run: cargo publish -p meta-mcp --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true

  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest
    # Only update on non-prerelease tags
    if: ${{ !contains(needs.release.outputs.tag, '-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract version
        id: version
        run: echo "version=${TAG#v}" >> $GITHUB_OUTPUT
        env:
          TAG: ${{ needs.release.outputs.tag }}

      - name: Calculate checksums
        id: checksums
        run: |
          # Read checksums from sha256 files
          DARWIN_ARM64=$(cat artifacts/meta-darwin-arm64.tar.gz/meta-darwin-arm64.tar.gz.sha256 | awk '{print $1}')
          DARWIN_X64=$(cat artifacts/meta-darwin-x64.tar.gz/meta-darwin-x64.tar.gz.sha256 | awk '{print $1}')
          LINUX_ARM64=$(cat artifacts/meta-linux-arm64.tar.gz/meta-linux-arm64.tar.gz.sha256 | awk '{print $1}')
          LINUX_X64=$(cat artifacts/meta-linux-x64.tar.gz/meta-linux-x64.tar.gz.sha256 | awk '{print $1}')

          echo "darwin_arm64=$DARWIN_ARM64" >> $GITHUB_OUTPUT
          echo "darwin_x64=$DARWIN_X64" >> $GITHUB_OUTPUT
          echo "linux_arm64=$LINUX_ARM64" >> $GITHUB_OUTPUT
          echo "linux_x64=$LINUX_X64" >> $GITHUB_OUTPUT

      - name: Generate Homebrew formula
        run: |
          cat > meta-cli.rb << 'FORMULA'
          # typed: false
          # frozen_string_literal: true

          class MetaCli < Formula
            desc "Multi-repo management CLI with AI integration"
            homepage "https://github.com/harmony-labs/meta"
            version "${{ steps.version.outputs.version }}"
            license "MIT"

            on_macos do
              on_arm do
                url "https://github.com/harmony-labs/meta/releases/download/v#{version}/meta-darwin-arm64.tar.gz"
                sha256 "${{ steps.checksums.outputs.darwin_arm64 }}"
              end
              on_intel do
                url "https://github.com/harmony-labs/meta/releases/download/v#{version}/meta-darwin-x64.tar.gz"
                sha256 "${{ steps.checksums.outputs.darwin_x64 }}"
              end
            end

            on_linux do
              on_arm do
                url "https://github.com/harmony-labs/meta/releases/download/v#{version}/meta-linux-arm64.tar.gz"
                sha256 "${{ steps.checksums.outputs.linux_arm64 }}"
              end
              on_intel do
                url "https://github.com/harmony-labs/meta/releases/download/v#{version}/meta-linux-x64.tar.gz"
                sha256 "${{ steps.checksums.outputs.linux_x64 }}"
              end
            end

            def install
              bin.install "meta"
              bin.install "meta-git"
              bin.install "meta-project"
              bin.install "meta-mcp"
              bin.install "loop"
            end

            test do
              system "#{bin}/meta", "--version"
            end
          end
          FORMULA

      - name: Push to Homebrew tap
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          BRANCH="update-meta-cli-${VERSION}"

          gh auth setup-git
          gh repo clone harmony-labs/homebrew-tap tap
          mkdir -p tap/Formula
          cp meta-cli.rb tap/Formula/
          cd tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/meta-cli.rb
          if ! git diff --cached --quiet; then
            git checkout -b "$BRANCH"
            git commit -m "Update meta-cli to v${VERSION}"
            # Force push in case branch exists from a previous failed run
            git push -f -u origin "$BRANCH"
            # Create PR only if one doesn't already exist
            if ! gh pr view "$BRANCH" --repo harmony-labs/homebrew-tap &>/dev/null; then
              gh pr create \
                --title "Update meta-cli to v${VERSION}" \
                --body "Automated formula update from meta release v${VERSION}." \
                --repo harmony-labs/homebrew-tap
            fi
            gh pr merge "$BRANCH" \
              --auto --squash \
              --repo harmony-labs/homebrew-tap || echo "Auto-merge setup failed (may require approvals)"
          else
            echo "Formula unchanged, skipping commit"
          fi
